name: "estude"
services:
  estude-web-application:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: estude-app
    volumes:
      - estude-db:/app/src/database
    networks:
      - estude-network

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    container_name: estude-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - estude-web-application
    networks:
      - estude-network

volumes:
  estude-db:
    name: "estude-db"

networks:
  estude-network:
    name: "estude-network"